[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18" }

# Required for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Explicit Edge Functions declaration (optional but recommended)
[[edge_functions]]
  path = "/*"
  function = "middleware"

# Next.js image optimization redirects
[[redirects]]
  from = "/_next/image"
  query = { url = ":url", w = ":width", q = ":quality" }
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200

[[redirects]]
  from = "/_ipx/*"
  query = { url = ":url", w = ":width", q = ":quality" }
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200